[tool.poetry]
name = "wlands-backend"
version = "0.1.0"
description = ""
authors = ["RuslanUC <dev_ruslan_uc@protonmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.116.1"
uvicorn = "^0.35.0"
tortoise-orm = {extras = ["asyncmy", "accel"], version = "^0.25.1"}
pycryptodome = "^3.23.0"
bcrypt = "^4.3.0"
python-magic = "^0.4.27"
pillow = "^11.3.0"
s3lite = "^0.1.11"
pydantic = {extras = ["email"], version = "2.9.2"}
aerich = "^0.9.1"
python-multipart = "^0.0.20"
pydantic-xml = "^2.17.3"
jinja2 = "^3.1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
